a_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from a_users.views import profile_view
from a_home.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('nameh.urls')),
    path('profile/', include('a_users.urls')),
    path('@<username>/', profile_view, name="profile"),
]

# Only used when DEBUG=True, whitenoise can serve files when DEBUG=False
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
    ]

nameh/urls.py
from django.urls import path
from .views import chat_view, get_or_create_chatroom, create_groupchat, chatroom_edit_view, chatroom_delete_view, \
    chatroom_leave_view , chat_file_upload
urlpatterns = [
    path("", chat_view, name="chat_view"),
    path('chat/new_groupchat/', create_groupchat, name="new-groupchat"),
    path('chat/<username>', get_or_create_chatroom, name="start-chat"),
    path("chat/<str:chatroom_name>/", chat_view, name="chatroom"),
    path('chat/edit/<chatroom_name>', chatroom_edit_view, name="edit-chatroom"),
    path('chat/delete/<chatroom_name>', chatroom_delete_view, name="chatroom-delete"),
    path('chat/leave/<chatroom_name>', chatroom_leave_view, name="chatroom-leave"),
    path('chat/fileupload/<chatroom_name>', chat_file_upload, name="chat-file-upload"),
]

nameh/models.py
from django.db import models
from django.contrib.auth.models import User
import shortuuid
import os
from PIL import Image

class ChatGroup(models.Model):
    group_name = models.CharField(max_length=128, unique=True, blank=True , default=shortuuid.uuid)
    groupchat_name = models.CharField(max_length=128, null=True, blank=True)
    admin = models.ForeignKey(User, related_name='groupchats', blank=True, null=True, on_delete=models.SET_NULL)
    users_online = models.ManyToManyField(User, related_name='online_in_groups', blank=True)
    members = models.ManyToManyField(User, related_name='chat_groups', blank=True)
    is_private = models.BooleanField(default=False)


    def __str__(self):
        return self.group_name




class GroupMessage(models.Model):
    group = models.ForeignKey(ChatGroup, related_name='chat_messages', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.CharField(max_length=300, blank=True, null=True)
    file = models.FileField(upload_to='files/', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)


    @property
    def filename(self):
        if self.file:
            return os.path.basename(self.file.name)
        else :
            return None


    def __str__(self):
        if self.body:
            return f'{self.author.username} : {self.body}'
        elif self.file :
            return f'{self.author.username} : {self.filename}'


    class Meta:
        ordering = ['-created']


    @property
    def is_image(self):
        if self.filename and self.filename.lower().endswith(('.jpg', '.jpeg', '.png', '.gif', '.svg', '.webp')):
            return True
        return False

nameh/forms.py
from django.forms import ModelForm
from django import forms
from .models import *


class ChatmessageCreateForm(ModelForm):
    class Meta:
        model = GroupMessage
        fields = ['body']
        widgets = {
            'body': forms.TextInput(
                attrs={'placeholder': 'Add message ...', 'class': 'p-4 text-black', 'maxlength': '300',
                       'autofocus': True}),
        }



class NewGroupForm(ModelForm):
    class Meta:
        model = ChatGroup
        fields = ['groupchat_name']
        widgets = {
            'groupchat_name' : forms.TextInput(attrs={
                'placeholder': 'Add name ...',
                'class': 'p-4 text-black',
                'maxlength' : '300',
                'autofocus': True,
                }),
        }

class ChatRoomEditForm(ModelForm):
    class Meta:
        model = ChatGroup
        fields = ['groupchat_name']
        widgets = {
            'groupchat_name' : forms.TextInput(attrs={
                'class': 'p-4 text-xl font-bold mb-4',
                'maxlength' : '300',
                }),
        }

nameh/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
from django.http import Http404
from django.contrib import messages
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from .forms import *
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.http import HttpResponse



@login_required
def chat_view(request, chatroom_name='public-chat'):
    chat_group = get_object_or_404(ChatGroup, group_name=chatroom_name)
    chat_messages = chat_group.chat_messages.all()[:30]
    form = ChatmessageCreateForm()

    other_user = None
    if chat_group.is_private:
        if request.user not in chat_group.members.all():
            raise Http404
        for member in chat_group.members.all():
            if member != request.user :
                other_user = member
                break

    if chat_group.groupchat_name:
        if request.user not in chat_group.members.all():
            if request.user.emailaddress_set.filter(verified=True).exists():
                chat_group.members.add(request.user)
            else:
                messages.warning(request, 'You need to verify your email to join the chat!')
                return redirect('profile-settings')

    if request.htmx:
        form = ChatmessageCreateForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.author = request.user
            message.group = chat_group
            message.save()

            # notify other websocket clients
            channel_layer = get_channel_layer()
            async_to_sync(channel_layer.group_send)(
                chatroom_name,
                {
                    'type': 'message_handler',
                    'message_id': message.id,
                }
            )

            return render(
                request,
                "nameh/partials/chat_message_p.html",
                {"message": message, "user": request.user}
            )


    context = {
        "chat_group": chat_group,
        "chat_messages": chat_messages,
        "form": form,
        "chatroom_name": chatroom_name,
        "online_count": chat_group.users_online.count(),
        "other_user" : other_user
    }

    return render(request, "nameh/chat.html", context)




@login_required
def get_or_create_chatroom(request, username):
    if request.user.username == username:
        return redirect('home')

    other_user = User.objects.get(username=username)
    my_private_chatrooms = request.user.chat_groups.filter(is_private=True)

    if my_private_chatrooms.exists():
        for chatroom in my_private_chatrooms:
            if other_user in chatroom.members.all():
                return redirect("chatroom" , chatroom.group_name)


    chatroom = ChatGroup.objects.create(is_private=True)
    chatroom.members.add(other_user, request.user)

    return redirect('chatroom', chatroom.group_name)


@login_required
def create_groupchat(request):
    form = NewGroupForm()

    if request.method == 'POST':
        form = NewGroupForm(request.POST)
        if form.is_valid():
            new_groupchat = form.save(commit=False)
            new_groupchat.admin = request.user
            new_groupchat.save()
            new_groupchat.members.add(request.user)
            return redirect('chatroom', new_groupchat.group_name)

    context = {
        'form': form
    }
    return render(request, 'nameh/create_groupchat.html', context)


@login_required
def chatroom_edit_view(request, chatroom_name):
    chat_group = get_object_or_404(ChatGroup, group_name=chatroom_name)
    if request.user != chat_group.admin:
        raise Http404()

    form = ChatRoomEditForm(instance=chat_group)

    if request.method == 'POST':
        form = ChatRoomEditForm(request.POST, instance=chat_group)
        if form.is_valid():
            form.save()

            remove_members = request.POST.getlist('remove_members')
            for member_id in remove_members:
                member = User.objects.get(id=member_id)
                chat_group.members.remove(member)

            return redirect('chatroom', chatroom_name)

    context = {
        'form': form,
        'chat_group': chat_group
    }
    return render(request, 'nameh/chatroom_edit.html', context)


@login_required
def chatroom_delete_view(request, chatroom_name):
    chat_group = get_object_or_404(ChatGroup, group_name=chatroom_name)
    if request.user != chat_group.admin:
        raise Http404()

    if request.method == "POST":
        chat_group.delete()
        messages.success(request, 'Chatroom deleted')
        return redirect('home')

    return render(request, 'nameh/chatroom_delete.html', {'chat_group': chat_group})


@login_required
def chatroom_leave_view(request, chatroom_name):
    chat_group = get_object_or_404(ChatGroup, group_name=chatroom_name)
    if request.user not in chat_group.members.all():
        raise Http404()

    if request.method == "POST":
        chat_group.members.remove(request.user)
        messages.success(request, 'You left the Chat')
        return redirect('chat_view')


def chat_file_upload(request, chatroom_name):
    chat_group = get_object_or_404(ChatGroup, group_name=chatroom_name)

    if request.htmx and request.FILES:
        file = request.FILES['file']
        message = GroupMessage.objects.create(
            file=file,
            author=request.user,
            group=chat_group,
        )
        channel_layer = get_channel_layer()
        event = {
            'type': 'message_handler',
            'message_id': message.id,
        }
        async_to_sync(channel_layer.group_send)(
            chatroom_name, event
        )
        html = render_to_string(
            "nameh/partials/chat_message_p.html",
            {"message": message, "user": request.user}
        )
        return HttpResponse(html)

nameh/templates/nameh/chat.html
{% extends 'layouts/blank.html' %}


{% block content %}
<div class="block max-w-2xl mx-auto my-10 px-6">
    {% if chat_group.groupchat_name %}
    <div class="flex justify-between">
        <h2 class="text-xl font-bold">{{ chat_group.groupchat_name }}</h2>
        {% if user == chat_group.admin %}
        <a href="{% url 'edit-chatroom' chat_group.group_name %}">
            <div class="p-2 bg-gray-200 hover:bg-blue-600 rounded-lg group">
                <svg class="fill-gray-500 group-hover:fill-white" width="16" height="16">
                    <path d="M11.013 1.427a1.75 1.75 0 0 1 2.474 0l1.086 1.086a1.75 1.75 0 0 1 0 2.474l-8.61 8.61c-.21.21-.47.364-.756.445l-3.251.93a.75.75 0 0 1-.927-.928l.929-3.25c.081-.286.235-.547.445-.758l8.61-8.61Zm.176 4.823L9.75 4.81l-6.286 6.287a.253.253 0 0 0-.064.108l-.558 1.953 1.953-.558a.253.253 0 0 0 .108-.064Zm1.238-3.763a.25.25 0 0 0-.354 0L10.811 3.75l1.439 1.44 1.263-1.263a.25.25 0 0 0 0-.354Z"></path>
                </svg>
            </div>
        </a>
        {% endif %}

    </div>
    {% endif %}

    <div id="chat_window" class="h-[45rem] flex flex-col bg-gray-800 rounded-2xl shadow-2xl relative p-1">
        <!-- Chat header -->
        <div class="flex justify-center text-emerald-400 bg-gray-800 p-2 sticky top-0 z-10">
            {% if other_user %}
            <div id="online-icon" class="gray-dot absolute top-2 left-2"></div>
            <a href="{% url 'profile' other_user.username %}">
                <div class="flex items-center gap-2 p-4">
                    <img class="w-10 h-10 rounded-full object-cover" src="{{ other_user.profile.avatar }}"/>
                    <div>
                        <span class="font-bold text-white">{{ other_user.profile.name }}</span>
                        <span class="text-sm font-light text-gray-400">@{{ other_user.username }}</span>
                    </div>
                </div>
            </a>

            {% elif chat_group.groupchat_name %}
            <ul id="groupchat-members" class="flex gap-4">
                {% for member in chat_group.members.all %}
                <li>
                    <a href="{% url 'profile' member.username %}"
                       class="flex flex-col text-gray-400 items-center justify-center w-20 gap-2">
                        <img src="{{ member.profile.avatar }}" class="w-14 h-14 rounded-full object-cover"/>
                        {{ member.profile.name|slice:":10" }}
                    </a>
                </li>
                {% endfor %}
            </ul>
            {% else %}


            <div id="online-icon"></div>
            <span id="online-count" class="pr-1">{{ online_count }}</span> online

            {% endif %}
        </div>

        <!-- Chat container -->
        <div id="chat_container" class="overflow-y-auto grow">
            <ul id="chat_messages" class="flex flex-col justify-end gap-2 p-4">
                {% for message in chat_messages reversed %}
                {% include 'nameh/chat_message.html' %}
                {% endfor %}
            </ul>
        </div>

        <!-- Message form -->
        <div class="sticky bottom-0 z-10 p-2 bg-gray-800">
            <div class="flex flex-col gap-4 items-center rounded-xl px-2 py-2">
                <form id="chat_message_form" class="w-full"
                      hx-post="{% url 'chatroom' chatroom_name %}"
                      hx-target="#chat_messages"
                      ws-connect="/ws/chatroom/{{ chatroom_name }}"
                      hx-swap="beforeend"
                      _="on htmx:afterOnLoad reset() me">
                    {% csrf_token %}
                    {{ form }}
                </form>

                <form id="chat_file_form" enctype="multipart/form-data" class="flex items-center w-full"
                      hx-post="{% url 'chat-file-upload' chat_group.group_name %}"
                      hx-target="#chat_messages"
                      hx-swap="beforeend"
                      _="on htmx:beforeSend reset() me">
                    {% csrf_token %}
                    <input type="file" name="file" id="id_file" class="!bg-transparent text-gray-400">
                    <button type="submit" class="whitespace-nowrap !text-sm !py-3 !px-4 h-fit">Submit File</button>
                </form>

            </div>
        </div>
    </div>

    {% if chat_group.members.exists %}
    <div x-data="{ modal_open: false }" class="mt-4 flex justify-center">
        <button
                @click="modal_open = true"
                class="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition"
        >
            Leave Chat
        </button>

        {% include 'nameh/partials/modal_chat_leave.html' %}
    </div>
    {% endif %}


</div>
{% endblock %}

{% block javascript %}

<script>

    (function() {
        const roomName = "{{ chatroom_name }}";
        const protocol = window.location.protocol === "https:" ? "wss://" : "ws://";
        const host = window.location.host;

        // --- CHAT SOCKET ---
        const chatSocket = new WebSocket(`${protocol}${host}/ws/chat/${roomName}/`);
        chatSocket.onopen = () => console.log("Chat socket connected:", roomName);
        chatSocket.onmessage = (e) => {
            const html = e.data;
            if (html.includes('id="online-count"')) {
                const temp = document.createElement('div');
                temp.innerHTML = html;
                const incoming = temp.querySelector('#online-count');
                const existing = document.getElementById('online-count');
                if (incoming && existing) existing.outerHTML = incoming.outerHTML;
                return;
            }
            document.getElementById('chat_messages')?.insertAdjacentHTML('beforeend', html);
            scrollToBottom(200);  // ⬅ scroll down after receiving message
        };

        // --- GLOBAL ONLINE STATUS SOCKET ---
        const onlineSocket = new WebSocket(`${protocol}${host}/ws/online-status/`);
        onlineSocket.onopen = () => console.log("Connected to /ws/online-status/");
        onlineSocket.onmessage = (e) => {
            const html = e.data;
            const container = document.getElementById('online-user-count');
            if (container) {
                container.outerHTML = html;
            }
        };
        onlineSocket.onclose = () => console.log("Disconnected from /ws/online-status/");

        // --- SCROLL HELPER ---
        function scrollToBottom(time = 0) {
            setTimeout(() => {
                const container = document.getElementById('chat_container');
                if (container) container.scrollTop = container.scrollHeight;
            }, time);
        }

        // --- FILE UPLOAD FORM ---
        const fileForm = document.getElementById('chat_file_form');
        if (fileForm) {
            fileForm.addEventListener('htmx:afterRequest', () => {
                // give Django a sec to render the image URL
                setTimeout(() => {
                    location.reload();  // reload chat after upload
                }, 800);
            });
        }
    })();
</script>


<style>
    @keyframes fadeInAndUp {
        from { opacity: 0; transform: translateY(12px); }
        to { opacity: 1; transform: translateY(0px); }
    }
    .fade-in-up {
        animation: fadeInAndUp 0.6s ease;
    }
</style>
{% endblock %}

nameh/templates/nameh/chat_message.html
{% if message.author == user %}
<li class="flex justify-end mb-4">
    <div class="bg-green-200 rounded-l-lg rounded-tr-lg p-4 max-w-[75%]">
        {% include 'nameh/partials/message_content.html' %}
    </div>
    <div class="flex items-end">
        <svg height="13" width="8">
            <path fill="#bbf7d0" d="M6.3,10.4C1.5,8.7,0.9,5.5,0,0.2L0,13l5.2,0C7,13,9.6,11.5,6.3,10.4z"/>
        </svg>
    </div>
</li>
{% else %}

<li class="flex justify-start mb-4">
    <div class="flex items-end mr-2">
        <div class="relative">
            <a href="{% url 'start-chat' message.author.username %}">
                <img class="w-8 h-8 rounded-full object-cover"
                     src="{{ message.author.profile.avatar }}"
                     alt="{{ message.author.username }}">
            </a>


        </div>
    </div>
    <div class="flex items-end">
        <svg height="13" width="8">
            <path fill="white" d="M2.8,13L8,13L8,0.2C7.1,5.5,6.5,8.7,1.7,10.4C-1.6,11.5,1,13,2.8,13z"></path>
        </svg>
    </div>
    <div class="bg-white p-4 max-w-[75%] rounded-r-lg rounded-tl-lg">
        {% include 'nameh/partials/message_content.html' %}
    </div>
</li>
{% endif %}

nameh/templates/nameh/chatroom_delete.html
{% extends 'layouts/box.html' %}

{% block content %}

<h1>Delete this chatroom?</h1>

<h2>"{{ chat_group.groupchat_name }}"</h2>

<form method='POST'>
    {% csrf_token %}
    <button type="submit" class="button-red mt-4">Yes, delete</button>
    <a class="button button-gray ml-1" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
</form>

{% endblock %}

nameh/templates/nameh/chatroom_edit.html
{% extends 'layouts/box.html' %}

{% block content %}

<h1>Edit Chat</h1>

<form method="post">
    {% csrf_token %}
    {{ form }}

    <div class="my-4">
    <h2>Members</h2>
    {% for member in chat_group.members.all %}
    <div class="flex justify-between items-center">
        <div class="flex items-center gap-2 py-2">
            <img class="w-14 h-14 rounded-full object-cover" src="{{ member.profile.avatar }}" />
            <div>
                <span class="font-bold">{{ member.profile.name }}</span>
                <span class="text-sm font-light text-gray-600">@{{ member.username }}</span>
            </div>
        </div>

        {% if member != chat_group.admin %}
        <div class="inline-block pr-4">
            <input type="checkbox" name="remove_members" value="{{ member.id }}" class="relative p-5 cursor-pointer appearance-none rounded-md border after:absolute after:left-0 after:top-0 after:h-full after:w-full after:bg-[url('https://img.icons8.com/ffffff/32/multiply.png')] after:bg-center checked:bg-red-500 hover:ring hover:ring-gray-300 focus:outline-none" />
        </div>
        {% endif %}
    </div>
    {% endfor %}
    </div>

    <button class="mt-2" type="submit">Update</button>
</form>

<a href="{% url 'chatroom-delete' chat_group.group_name %}" class="flex justify-end mt-4 text-gray-400 hover:text-red-500" >Delete Chatroom</a>

{% endblock %}

nameh/templates/nameh/create_groupchat.html
{% extends 'layouts/box.html' %}

{% block content %}

<h1>New Group Chat</h1>

<form method="post">
    {% csrf_token %}
    {{ form }}
    <button class="mt-2" type="submit">Create Group Chat</button>
</form>

{% endblock %}